# [theme]
# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"

[theme]
primaryColor = "#d0e8f2" # light cyan
backgroundColor = "#fffefd" # extra light beige
secondaryBackgroundColor = "#e4f2f8" # dark cyan
textColor = "#000" # black
font = "sans serif"
baseFontSize = 18  

[logger]
level = "info


